apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  capacity:
    storage: 1Gi
  gcePersistentDisk:
    fsType: ext4
    pdName: mongodb
  persistentVolumeReclaimPolicy: Delete
