apiVersion: v1
kind: Service
metadata:
  labels:
    app: fortune
  name: fortune-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: fortune
  sessionAffinity: None
  type: LoadBalancer
