apiVersion: v1
data:
  my-nginx-config.conf: "server {\n  listen              80;\n  server_name         www.kubia-example.com;\n\n
    \ gzip off;                                       \n  gzip_types text/plain application/xml;
    \        \n\n  location / {\n    root   /usr/share/nginx/html;\n    index  index.html
    index.htm;\n ssl_certificate: certs/https.cert; \n ssl_certificate_key: certs/https.key; \n  }\n}\n"
  sleep-interval: |
    25
kind: ConfigMap
metadata:
  creationTimestamp: "2019-12-25T16:17:46Z"
  name: fortune-config
  namespace: default
  resourceVersion: "309787"
  selfLink: /api/v1/namespaces/default/configmaps/fortune-config
  uid: 1685b421-2732-11ea-976d-025000000001
