apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-without-sa
  name: pod-without-sa
spec:
  automountServiceAccountToken: false
  containers:
  - image: nginx
    name: pod-without-sa
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
