apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubia
  name: kubia-svc-nodeport
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: kubia
