apiVersion: v1
kind: Service
metadata:
  name: kubia-headless-all-pods
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: kubia
