apiVersion: v1
kind: Pod
metadata:
  labels:
    app: fortune
  name: fortune-pod
spec:
  volumes:
    - name: html
      emptyDir: {}
  containers:
  - image: nginx
    name: web-server
    ports:
      - containerPort: 80
        protocol: TCP
    volumeMounts:
      - name: html                           
        mountPath: /usr/share/nginx/html     
        readOnly: true
  - image: anandaili/fortune:env
    name: html-generator
    env:
      - name: INTERVAL
        valueFrom:
          configMapKeyRef:
            name: fortune-config
            key: sleep-interval
    volumeMounts:
      - name: html 
        mountPath: /var/htdocs 
       
    
