apiVersion: v1
kind: Pod
metadata:
  labels:
  name: gitrepo-volum-pod
spec:
  containers:
  - image: nginx
    name: web-server
    volumeMounts:
      - name: html
        mountPath: /usr/share/nginx/html
        readOnly: true
  - image: anandaili/gitsync:latest
    name: sync
    volumeMounts:
      - name: html
        mountPath: /var/htdocs
  volumes:
    - name: html
      gitRepo:
        directory: .
        repository: https://github.com/AnandAili/kubia-website-example.git
        revision: master
